<?php

declare(strict_types=1);

use App\Http\View\HtmlEscaper;

$t = $data['t'];
$escape = static fn (mixed $value): string => HtmlEscaper::escape($value);
$employee = is_array($data['employee'] ?? null) ? $data['employee'] : [];
$active = is_array($data['activeRecords'] ?? null) ? $data['activeRecords'] : [];
$archived = is_array($data['archivedRecords'] ?? null) ? $data['archivedRecords'] : [];
$id = (int) ($employee['id'] ?? 0);
?>
<section class="page-section"><?php $data['pageEyebrowKey'] = 'employees.portfolio'; $data['pageDescriptionKey'] = 'employees.certifications_description'; $data['pageActions'] = [['href' => '/employees/' . $id, 'labelKey' => 'actions.back_to_employee', 'variant' => 'text']]; include __DIR__ . '/../partials/page-header.php'; ?>
<div class="card detail-card"><div class="card-header"><div><p class="eyebrow"><?= $escape(($employee['last_name'] ?? '') . ' ' . ($employee['first_name'] ?? '')) ?></p><h2><?= $escape($t('employees.certifications_heading')) ?></h2></div><?php if (($employee['status'] ?? '') === 'active'): ?><a class="button button--primary" href="/employees/<?= $id ?>/certifications/create"><?= $escape($t('actions.add_certification')) ?></a><?php endif; ?></div>
<?php if (($data['notice'] ?? null) === 'created'): ?><div class="alert alert--success" role="status"><?= $escape($t('employees.portfolio_created')) ?></div><?php elseif (($data['notice'] ?? null) === 'restored'): ?><div class="alert alert--success" role="status"><?= $escape($t('employees.portfolio_restored')) ?></div><?php elseif (($data['notice'] ?? null) === 'updated'): ?><div class="alert alert--success" role="status"><?= $escape($t('employees.portfolio_updated')) ?></div><?php elseif (($data['notice'] ?? null) === 'archived'): ?><div class="alert alert--success" role="status"><?= $escape($t('employees.portfolio_archived')) ?></div><?php elseif (($data['notice'] ?? null) === 'already-archived'): ?><div class="alert alert--info" role="status"><?= $escape($t('employees.portfolio_already_archived')) ?></div><?php elseif (($data['notice'] ?? null) === 'inactive-edit'): ?><div class="alert alert--info" role="status"><?= $escape($t('employees.portfolio_inactive_notice')) ?></div><?php endif; ?>
<?php if (($employee['status'] ?? '') !== 'active'): ?><div class="alert alert--info" role="status"><?= $escape($t('employees.portfolio_read_only')) ?></div><?php endif; ?>
<?php if ($active === []): ?><p class="muted-text"><?= $escape($t('employees.no_certifications')) ?></p><?php else: ?><div class="table-scroll"><table class="data-table"><thead><tr><th><?= $escape($t('portfolio.certification_name')) ?></th><th><?= $escape($t('portfolio.issuing_organization')) ?></th><th><?= $escape($t('portfolio.obtained_date')) ?></th><th><?= $escape($t('portfolio.expiration_date')) ?></th><th><span class="visually-hidden"><?= $escape($t('table.actions')) ?></span></th></tr></thead><tbody>
<?php foreach ($active as $certification): ?><tr><td><a class="table-primary-link" href="/employees/<?= $id ?>/certifications/<?= (int) $certification['id'] ?>"><?= $escape($certification['certification_name']) ?></a></td><td><?= $escape($certification['issuing_organization']) ?></td><td><?= $escape($certification['obtained_date']) ?></td><td><?= $escape($certification['expiration_date'] ?? $t('portfolio.no_expiration')) ?></td><td><div class="table-actions"><?php if (($employee['status'] ?? '') === 'active'): ?><a class="button button--text button--small" href="/employees/<?= $id ?>/certifications/<?= (int) $certification['id'] ?>/edit"><?= $escape($t('actions.edit')) ?></a><a class="button button--text button--small button--danger-text" href="/employees/<?= $id ?>/certifications/<?= (int) $certification['id'] ?>/archive"><?= $escape($t('actions.archive')) ?></a><?php endif; ?></div></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?></div>
<div class="card detail-card"><div class="card-header"><div><p class="eyebrow"><?= $escape($t('employees.portfolio_history')) ?></p><h2><?= $escape($t('employees.archived_certifications')) ?></h2></div></div><?php if ($archived === []): ?><p class="muted-text"><?= $escape($t('employees.no_archived_certifications')) ?></p><?php else: ?><div class="table-scroll"><table class="data-table"><thead><tr><th><?= $escape($t('portfolio.certification_name')) ?></th><th><?= $escape($t('portfolio.issuing_organization')) ?></th><th><?= $escape($t('portfolio.archived_at')) ?></th></tr></thead><tbody><?php foreach ($archived as $certification): ?><tr><td><a class="table-primary-link" href="/employees/<?= $id ?>/certifications/<?= (int) $certification['id'] ?>"><?= $escape($certification['certification_name']) ?></a></td><td><?= $escape($certification['issuing_organization']) ?></td><td><?= $escape($certification['archived_at'] ?? '') ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></section>

