<?php
declare(strict_types=1);
use App\Http\View\HtmlEscaper;
$t = $data['t'];
$escape = static fn (mixed $value): string => HtmlEscaper::escape($value);
$employeeId = (int) $data['employee']['id'];
$certification = $data['certification'];
$certificationId = (int) $certification['id'];
?>
<section class="page-section"><?php $data['pageEyebrowKey'] = 'employees.portfolio'; $data['pageDescriptionKey'] = 'employees.certification_detail_description'; $data['pageActions'] = [['href' => '/employees/' . $employeeId . '/certifications', 'labelKey' => 'actions.back_to_certifications', 'variant' => 'text']]; include __DIR__ . '/../partials/page-header.php'; ?><article class="card detail-card"><div class="card-header"><div><p class="eyebrow"><?= $escape(($data['employee']['last_name'] ?? '') . ' ' . ($data['employee']['first_name'] ?? '')) ?></p><h2><?= $escape($certification['certification_name'] ?? '') ?></h2></div><?php $chipLabelKey = ($certification['status'] ?? '') === 'active' ? 'portfolio.status_active' : 'portfolio.status_archived'; $chipTone = ($certification['status'] ?? '') === 'active' ? 'success' : 'neutral'; include __DIR__ . '/../partials/status-chip.php'; ?></div><dl class="detail-list"><div><dt><?= $escape($t('portfolio.issuing_organization')) ?></dt><dd><?= $escape($certification['issuing_organization'] ?? '') ?></dd></div><div><dt><?= $escape($t('portfolio.obtained_date')) ?></dt><dd><?= $escape($certification['obtained_date'] ?? '') ?></dd></div><div><dt><?= $escape($t('portfolio.expiration_date')) ?></dt><dd><?= $escape($certification['expiration_date'] ?? $t('portfolio.no_expiration')) ?></dd></div><div><dt><?= $escape($t('portfolio.credential_identifier')) ?></dt><dd><?= $escape($certification['credential_identifier'] ?? $t('status.not_provided')) ?></dd></div><div><dt><?= $escape($t('portfolio.notes')) ?></dt><dd><?= nl2br($escape($certification['notes'] ?? $t('status.not_provided'))) ?></dd></div></dl><div class="detail-footer-actions"><?php if (($data['employee']['status'] ?? '') === 'active' && ($certification['status'] ?? '') === 'active' && ($data['isAdmin'] ?? false)): ?><a class="button button--secondary" href="/employees/<?= $employeeId ?>/certifications/<?= $certificationId ?>/edit"><?= $escape($t('actions.edit')) ?></a><a class="button button--danger" href="/employees/<?= $employeeId ?>/certifications/<?= $certificationId ?>/archive"><?= $escape($t('actions.archive')) ?></a><?php endif; ?></div></article></section>
