<?php

declare(strict_types=1);

use App\Http\View\HtmlEscaper;

$t = $data['t'] ?? static fn (string $key, array $replace = []): string => $key;
$department = is_array($data['department'] ?? null) ? $data['department'] : [];
$employees = is_array($department['employees'] ?? null) ? $department['employees'] : [];
$escape = static fn (mixed $value): string => HtmlEscaper::escape($value);
$id = (int) ($department['id'] ?? 0);
?>
<section class="page-section">
    <?php $data['pageEyebrowKey'] = 'departments.directory'; $data['pageDescriptionKey'] = 'departments.detail_description'; $data['pageActions'] = [['href' => '/departments', 'labelKey' => 'actions.back_to_departments', 'variant' => 'text'], ['href' => '/departments/' . $id . '/edit', 'labelKey' => 'actions.edit_department', 'variant' => 'secondary']]; include __DIR__ . '/../partials/page-header.php'; ?>
    <?php if (($data['notice'] ?? null) === 'deactivated'): ?><div class="alert alert--success" role="status"><?= $escape($t('departments.deactivated_success')) ?></div><?php elseif (($data['notice'] ?? null) === 'already-inactive'): ?><div class="alert alert--info" role="status"><?= $escape($t('departments.already_inactive_notice')) ?></div><?php endif; ?>
    <div class="detail-grid"><article class="card detail-card"><div class="card-header"><div><p class="eyebrow"><?= $escape($t('departments.department_information')) ?></p><h2><?= $escape($department['name'] ?? '') ?></h2><p class="muted-text"><?= $escape(($department['company_code'] ?? '') . ' ' . ($department['company_name'] ?? '') . ' · ' . ($department['branch_code'] ?? '') . ' ' . ($department['branch_name'] ?? '')) ?></p></div><?php $chipLabelKey = ($department['status'] ?? '') === 'active' ? 'status.active' : 'status.inactive'; $chipTone = ($department['status'] ?? '') === 'active' ? 'success' : 'neutral'; include __DIR__ . '/../partials/status-chip.php'; ?></div><dl class="detail-list"><div><dt><?= $escape($t('form.department_code')) ?></dt><dd class="code-text"><?= $escape($department['code'] ?? '') ?></dd></div><div><dt><?= $escape($t('form.branch')) ?></dt><dd><?= $escape(($department['branch_code'] ?? '') . ' ' . ($department['branch_name'] ?? '')) ?><?php if (($department['branch_status'] ?? '') !== 'active'): ?> <span class="muted-text">(<?= $escape($t('status.inactive')) ?>)</span><?php endif; ?></dd></div><div><dt><?= $escape($t('form.description')) ?></dt><dd><?= nl2br($escape($department['description'] ?? $t('status.not_provided'))) ?></dd></div><div><dt><?= $escape($t('departments.created')) ?></dt><dd><?= $escape($department['created_at'] ?? '') ?></dd></div><div><dt><?= $escape($t('departments.updated')) ?></dt><dd><?= $escape($department['updated_at'] ?? '') ?></dd></div></dl></article><article class="card detail-card"><div class="card-header"><div><p class="eyebrow"><?= $escape($t('departments.related_employees')) ?></p><h2><?= $escape($t('departments.employee_count', ['count' => (string) count($employees)])) ?></h2></div></div><?php if ($employees === []): ?><p class="muted-text"><?= $escape($t('departments.no_employees')) ?></p><?php else: ?><div class="table-scroll"><table class="data-table"><thead><tr><th><?= $escape($t('table.code')) ?></th><th><?= $escape($t('table.name')) ?></th><th><?= $escape($t('table.type')) ?></th><th><?= $escape($t('table.status')) ?></th></tr></thead><tbody><?php foreach ($employees as $employee): ?><tr><td class="code-text"><?= $escape($employee['employee_code']) ?></td><td><a class="table-primary-link" href="/employees/<?= (int) $employee['id'] ?>"><?= $escape($employee['last_name'] . ' ' . $employee['first_name']) ?></a></td><td><?= $escape($t($employee['employee_type'] === 'dispatched' ? 'status.dispatched' : 'status.permanent')) ?></td><td><?php $chipLabelKey = ($employee['status'] ?? '') === 'active' ? 'status.active' : 'status.inactive'; $chipTone = ($employee['status'] ?? '') === 'active' ? 'success' : 'neutral'; include __DIR__ . '/../partials/status-chip.php'; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></article></div>
    <?php if (($department['status'] ?? null) === 'active'): ?><div class="detail-footer-actions"><a class="button button--danger" href="/departments/<?= $id ?>/deactivate"><?= $escape($t('actions.deactivate_department')) ?></a></div><?php endif; ?>
</section>
