<?php

declare(strict_types=1);

use App\Http\View\HtmlEscaper;

$t = $data['t'] ?? static fn (string $key, array $replace = []): string => $key;
$branch = is_array($data['branch'] ?? null) ? $data['branch'] : [];
$departments = is_array($branch['departments'] ?? null) ? $branch['departments'] : [];
$escape = static fn (mixed $value): string => HtmlEscaper::escape($value);
$id = (int) ($branch['id'] ?? 0);
?>
<section class="page-section">
    <?php $data['pageEyebrowKey'] = 'branches.directory'; $data['pageDescriptionKey'] = 'branches.detail_description'; $data['pageActions'] = [['href' => '/branches', 'labelKey' => 'actions.back_to_branches', 'variant' => 'text'], ['href' => '/branches/' . $id . '/edit', 'labelKey' => 'actions.edit_branch', 'variant' => 'secondary']]; include __DIR__ . '/../partials/page-header.php'; ?>
    <?php if (($data['notice'] ?? null) === 'deactivated'): ?><div class="alert alert--success" role="status"><?= $escape($t('branches.deactivated_success')) ?></div><?php elseif (($data['notice'] ?? null) === 'already-inactive'): ?><div class="alert alert--info" role="status"><?= $escape($t('branches.already_inactive_notice')) ?></div><?php endif; ?>
    <div class="detail-grid"><article class="card detail-card"><div class="card-header"><div><p class="eyebrow"><?= $escape($t('branches.branch_information')) ?></p><h2><?= $escape($branch['name'] ?? '') ?></h2><p class="muted-text"><?= $escape(($branch['company_code'] ?? '') . ' ' . ($branch['company_name'] ?? '')) ?></p></div><?php $chipLabelKey = ($branch['status'] ?? '') === 'active' ? 'status.active' : 'status.inactive'; $chipTone = ($branch['status'] ?? '') === 'active' ? 'success' : 'neutral'; include __DIR__ . '/../partials/status-chip.php'; ?></div><dl class="detail-list"><div><dt><?= $escape($t('form.branch_code')) ?></dt><dd class="code-text"><?= $escape($branch['code'] ?? '') ?></dd></div><div><dt><?= $escape($t('form.city')) ?></dt><dd><?= $escape($branch['city'] ?? '') ?></dd></div><div><dt><?= $escape($t('form.address')) ?></dt><dd><?= $escape($branch['address'] ?? '') ?></dd></div><div><dt><?= $escape($t('form.phone')) ?></dt><dd><?= $escape($branch['phone'] ?? '') ?></dd></div><div><dt><?= $escape($t('branches.created')) ?></dt><dd><?= $escape($branch['created_at'] ?? '') ?></dd></div><div><dt><?= $escape($t('branches.updated')) ?></dt><dd><?= $escape($branch['updated_at'] ?? '') ?></dd></div></dl></article><article class="card detail-card"><div class="card-header"><div><p class="eyebrow"><?= $escape($t('branches.related_departments')) ?></p><h2><?= $escape($t('branches.department_count', ['count' => (string) count($departments)])) ?></h2></div><a class="button button--primary" href="/departments/create"><?= $escape($t('actions.create_department')) ?></a></div><?php if ($departments === []): ?><p class="muted-text"><?= $escape($t('branches.no_departments')) ?></p><?php else: ?><div class="table-scroll"><table class="data-table"><thead><tr><th><?= $escape($t('form.department_code')) ?></th><th><?= $escape($t('form.department_name')) ?></th><th><?= $escape($t('table.employees')) ?></th><th><?= $escape($t('table.status')) ?></th></tr></thead><tbody><?php foreach ($departments as $department): ?><tr><td><span class="code-text"><?= $escape($department['code']) ?></span></td><td><a class="table-primary-link" href="/departments/<?= (int) $department['id'] ?>"><?= $escape($department['name']) ?></a></td><td><?= $escape($department['employee_count'] ?? 0) ?></td><td><?php $chipLabelKey = ($department['status'] ?? '') === 'active' ? 'status.active' : 'status.inactive'; $chipTone = ($department['status'] ?? '') === 'active' ? 'success' : 'neutral'; include __DIR__ . '/../partials/status-chip.php'; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></article></div>
    <?php if (($branch['status'] ?? null) === 'active'): ?><div class="detail-footer-actions"><a class="button button--danger" href="/branches/<?= $id ?>/deactivate"><?= $escape($t('actions.deactivate_branch')) ?></a></div><?php endif; ?>
</section>
